Title: ZID Charts
Airports:
  Bravo:
    - CVG
  Charlie:
    - CMH
    - CRW
    - DAY
    - EVV
    - IND
    - LEX
    - SDF
  Delta:
    - AID
    - BAK
    - BMG
    - FFO
    - FTK
    - HTS
    - HUF
    - ILN
    - LCK
    - LOU
    - LUK
    - MIE
    - OSU
    - OWB
    - PKB
    - TZR
